version: '2'

services:

  php_ldap_admin:
    build: php_ldap_admin/
    #image: philleconnect/php_ldap_admin:latest
    restart: always
    links:
      - "ldap"
    ports:
      - "89:80"
    container_name: php_ldap_admin
    hostname: php_ldap_admin
    # 'dpkg-reconfigure slapd' hangs when a domain with an underscore _ is used
    # (which is unfortunately docker-compose default behavior)
    # so an alias is necessary if no custom (separately started) network shall be used:
    networks:
      - philleconnect
    env_file:
      - ./settings.env
    #volumes:
    #  - philleconnect_admin_mysql:/var/lib/phpldap


networks:
    default:
        external:
            name: servercontainers_philleconnect
